import streamlit as st
import sys
import re
import io
from pathlib import Path

PROJECT_ROOT = Path(__file__).parent.parent.absolute()
sys.path.insert(0, str(PROJECT_ROOT))

from src.agents.orchestrator import run_research_crew

st.set_page_config(
    page_title="Healthcare AI Research Agent",
    page_icon="🏥",
    layout="wide"
)

st.title("🏥 Healthcare AI Research Agent")
st.caption("AI-powered medical literature research | PubMed + LLM | By Asif Nawaz, PMAS Arid Agriculture University")
st.divider()

# ── Sidebar ────────────────────────────────────────────────
with st.sidebar:
    st.header("⚙️ System Info")
    st.metric("LLM", "Llama 3.3-70B")
    st.metric("Data Source", "PubMed + Web")
    st.metric("Agent Type", "Research + Writer")
    st.divider()

    st.header("💡 Example Queries")
    examples = [
        "Latest treatments for Type 2 diabetes 2024",
        "Pakistan out-of-pocket health expenditure",
        "Immunotherapy effectiveness for cancer 2024",
        "Long-term effects of COVID-19",
        "Hypertension management guidelines 2024",
        "Mental health depression treatment outcomes",
        "Antibiotic resistance latest research",
    ]
    for ex in examples:
        if st.button(ex, use_container_width=True, key=ex):
            st.session_state["query"] = ex

    st.divider()
    st.markdown("""
    **How it works:**
    1. Enter medical question
    2. Agent searches PubMed
    3. LLM generates report
    4. Download as PDF or Markdown
    """)

# ── Main ───────────────────────────────────────────────────
col1, col2 = st.columns([3, 1])

with col1:
    query = st.text_area(
        "Enter your medical research question:",
        value=st.session_state.get("query", ""),
        height=100,
        placeholder="e.g. What are the latest treatments for Type 2 diabetes in 2024?"
    )

with col2:
    st.write("")
    st.write("")
    search = st.button(
        "🔍 Research & Generate Report",
        type="primary",
        use_container_width=True
    )

# ── PDF Generator ──────────────────────────────────────────
def generate_pdf(report: str, query: str) -> bytes:
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.units import inch
    from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
    from reportlab.lib.colors import HexColor

    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer, pagesize=A4,
        rightMargin=inch*0.8, leftMargin=inch*0.8,
        topMargin=inch*0.8, bottomMargin=inch*0.8
    )

    styles = getSampleStyleSheet()
    styles.add(ParagraphStyle(
        name='CustomTitle',
        fontSize=18, fontName='Helvetica-Bold',
        textColor=HexColor('#1F4E79'),
        spaceAfter=14
    ))
    styles.add(ParagraphStyle(
        name='CustomHeading',
        fontSize=13, fontName='Helvetica-Bold',
        textColor=HexColor('#1F4E79'),
        spaceBefore=12, spaceAfter=6
    ))
    styles.add(ParagraphStyle(
        name='CustomSubHeading',
        fontSize=11, fontName='Helvetica-Bold',
        textColor=HexColor('#2E75B6'),
        spaceBefore=8, spaceAfter=4
    ))
    styles.add(ParagraphStyle(
        name='CustomBody',
        fontSize=10, fontName='Helvetica',
        leading=15, spaceAfter=6
    ))
    styles.add(ParagraphStyle(
        name='CustomMeta',
        fontSize=9, fontName='Helvetica',
        textColor=HexColor('#666666'),
        spaceAfter=4
    ))

    story = []

    # Header
    story.append(Paragraph("Healthcare AI Research Report", styles['CustomTitle']))
    story.append(Paragraph(f"<b>Query:</b> {query}", styles['CustomBody']))
    story.append(Paragraph(
        "Generated by: Asif Nawaz | PMAS Arid Agriculture University | MPhil Economics",
        styles['CustomMeta']
    ))
    story.append(Paragraph(
        "Data: PubMed (2020-2024) | LLM: Llama 3.3-70B via Groq",
        styles['CustomMeta']
    ))
    story.append(Spacer(1, 14))

    # Process markdown lines
    for line in report.split('\n'):
        line = line.strip()
        if not line:
            story.append(Spacer(1, 5))
            continue

        # Clean markdown
        line = re.sub(r'\*\*(.*?)\*\*', r'<b>\1</b>', line)
        line = re.sub(r'\*(.*?)\*', r'<i>\1</i>', line)
        line = line.replace('&', '&amp;')

        if line.startswith('# '):
            story.append(Paragraph(line[2:], styles['CustomTitle']))
        elif line.startswith('## '):
            story.append(Paragraph(line[3:], styles['CustomHeading']))
        elif line.startswith('### '):
            story.append(Paragraph(line[4:], styles['CustomSubHeading']))
        elif line.startswith('- ') or line.startswith('* '):
            story.append(Paragraph(f"&bull; {line[2:]}", styles['CustomBody']))
        elif re.match(r'^\d+\.', line):
            story.append(Paragraph(line, styles['CustomBody']))
        else:
            story.append(Paragraph(line, styles['CustomBody']))

    doc.build(story)
    return buffer.getvalue()


# ── Results ────────────────────────────────────────────────
if search and query.strip():
    with st.spinner("🔬 Searching PubMed and generating report... (30-60 sec)"):
        try:
            report = run_research_crew(query)

            st.divider()
            st.subheader("📋 Medical Research Report")
            st.markdown(report)
            st.divider()

            # Download buttons
            col_md, col_pdf = st.columns(2)

            with col_md:
                st.download_button(
                    label="📥 Download (Markdown)",
                    data=report,
                    file_name=f"report_{query[:30].replace(' ', '_')}.md",
                    mime="text/markdown",
                    use_container_width=True
                )

            with col_pdf:
                try:
                    pdf_bytes = generate_pdf(report, query)
                    st.download_button(
                        label="📄 Download (PDF)",
                        data=pdf_bytes,
                        file_name=f"report_{query[:30].replace(' ', '_')}.pdf",
                        mime="application/pdf",
                        use_container_width=True
                    )
                except Exception as e:
                    st.error(f"PDF error: {e}")
                    st.info("Install: pip install reportlab")

        except Exception as e:
            st.error(f"Error: {e}")

elif search and not query.strip():
    st.warning("Please enter a research question!")

st.divider()
st.caption(
    "Data: PubMed + Web Search · "
    "LLM: Llama 3.3-70B via Groq · "
    "Asif Nawaz | PMAS Arid Agriculture University | MPhil Economics"
)